
services:
  backend:
    image: aamirali1/mern-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    image: aamirali1/mern-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
