apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: expensetracker
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-storage
  hostPath:       # For local testing; in production use storageClass with cloud provider
    path: /mnt/data