# FROM node 

# WORKDIR /myapp

# COPY . .

# RUN npm install

# EXPOSE 3000 

# CMD [ "npm","start" ]

FROM node

WORKDIR /myapp

COPY package*.json ./
RUN npm install

COPY . .

CMD ["npm", "start"]
